# Generated by Django 4.2.6 on 2025-02-05 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("superheroes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="enemy",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="power",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="superhero",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="city",
            table="cities",
        ),
        migrations.AlterModelTable(
            name="enemy",
            table="enemies",
        ),
        migrations.AlterModelTable(
            name="power",
            table="powers",
        ),
        migrations.AlterModelTable(
            name="superhero",
            table="superheroes",
        ),
    ]
