# Generated by Django 4.2.6 on 2025-02-04 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("superheroes", "0002_alter_city_id_alter_enemy_id_alter_power_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="city",
            table="cities",
        ),
        migrations.AlterModelTable(
            name="enemy",
            table="enemies",
        ),
        migrations.AlterModelTable(
            name="power",
            table="powers",
        ),
        migrations.AlterModelTable(
            name="superhero",
            table="superheroes",
        ),
    ]
