# Generated by Django 4.2.6 on 2025-02-05 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "superheroes",
            "0003_alter_city_table_alter_enemy_table_alter_power_table_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CityPlus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "cities_plus",
            },
        ),
        migrations.CreateModel(
            name="EnemyPlus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "enemies_plus",
            },
        ),
        migrations.CreateModel(
            name="PowerPlus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "powers_plus",
            },
        ),
        migrations.CreateModel(
            name="SuperheroPlus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("real_name", models.CharField(max_length=32)),
                ("secret_identity", models.CharField(max_length=32)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superheroes.cityplus",
                    ),
                ),
                ("enemies_plus", models.ManyToManyField(to="superheroes.enemyplus")),
                ("powers_plus", models.ManyToManyField(to="superheroes.powerplus")),
            ],
            options={
                "db_table": "superheroes_plus",
                "ordering": ["secret_identity"],
            },
        ),
        migrations.AddField(
            model_name="enemyplus",
            name="powers",
            field=models.ManyToManyField(to="superheroes.powerplus"),
        ),
    ]
