# Generated by Django 4.2.6 on 2025-02-05 02:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("superheroes", "0004_cityplus_enemyplus_powerplus_superheroplus_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="superheroplus",
            old_name="enemies_plus",
            new_name="enemies",
        ),
        migrations.RenameField(
            model_name="superheroplus",
            old_name="powers_plus",
            new_name="powers",
        ),
        migrations.AlterField(
            model_name="cityplus",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="enemyplus",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="powerplus",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="superheroplus",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
