# Generated by Django 4.2.6 on 2025-02-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("superheroes", "0005_rename_enemies_plus_superheroplus_enemies_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enemyplus",
            name="powers",
        ),
        migrations.RemoveField(
            model_name="superheroplus",
            name="city",
        ),
        migrations.RemoveField(
            model_name="superheroplus",
            name="enemies",
        ),
        migrations.RemoveField(
            model_name="superheroplus",
            name="powers",
        ),
        migrations.DeleteModel(
            name="CityPlus",
        ),
        migrations.DeleteModel(
            name="EnemyPlus",
        ),
        migrations.DeleteModel(
            name="PowerPlus",
        ),
        migrations.DeleteModel(
            name="SuperheroPlus",
        ),
    ]
